version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - "scbuildcodeunits"
    aliases:
      - basebuildallcodeunits
      - bb

  IcecastserverRunExample:
    desc: "IcecastServer: Run example"
    silent: true
    dir: "./IcecastServer/Other/Examples/MinimalDockerComposeFile"
    cmds:
      - "python3 RunExample.py"
    aliases:
      - icecastserverrunexample
