@startuml CodeUnits-Overview
skinparam defaultFontName "DejaVu Sans"
title CodeUnits of IcecastServer

[IcecastServer]
note as IcecastServerNote
  IcecastServer is a docker-image for simply running an Icecast-server in a docker-container.
end note
IcecastServer .. IcecastServerNote


@enduml
